package cmd

import (
	"encoding/base64"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/ldclabs/cose/cose"
	"github.com/ldclabs/cose/cwt"
	"github.com/ldclabs/cose/iana"
	"github.com/ldclabs/cose/key"
	"github.com/ldclabs/cose/key/ed25519"
	"github.com/spf13/cobra"
)

var cwtCmd = &cobra.Command{
	Use:   "cwt",
	Short: "Create a CWT (CBOR Web Token)",
	Long: `Create and sign a CWT using an Ed25519 private key.
The private key should be base64 or base64url-encoded CBOR (COSE Key format),
as generated by the 'keygen' command. It can be passed directly, or read
from a file by using --key @path/to/key.txt or --key path/to/key.txt.

Example:
  anda-cli cwt --key <base64url_private_key> --subject <user_id> --audience <space_id> --scope write
  anda-cli cwt --key ./private_key.txt --subject <user_id> --audience <space_id> --scope write
  anda-cli cwt --key <base64url_private_key> --subject <user_id> --audience "*" --scope "*" --expiration 3600`,
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		keyInput := secretFlag(cmd, "key", "ANDA_CWT_KEY")
		subject, _ := cmd.Flags().GetString("subject")
		audience, _ := cmd.Flags().GetString("audience")
		scope, _ := cmd.Flags().GetString("scope")
		issuer, _ := cmd.Flags().GetString("issuer")
		expSec, _ := cmd.Flags().GetInt64("expiration")

		if scope != "read" && scope != "write" && scope != "*" {
			return fmt.Errorf("invalid --scope %q", scope)
		}

		if keyInput == "" {
			return fmt.Errorf("--key is required")
		}
		if subject == "" {
			return fmt.Errorf("--subject is required")
		}
		if audience == "" {
			return fmt.Errorf("--audience is required")
		}

		keyData, err := readPrivateKeyData(keyInput)
		if err != nil {
			return err
		}

		var privKey key.Key
		if err := key.UnmarshalCBOR(keyData, &privKey); err != nil {
			return fmt.Errorf("unmarshal private key: %w", err)
		}

		if err := ed25519.CheckKey(privKey); err != nil {
			return fmt.Errorf("invalid Ed25519 key: %w", err)
		}

		signer, err := privKey.Signer()
		if err != nil {
			return fmt.Errorf("create signer: %w", err)
		}

		now := time.Now()
		if expSec <= 0 {
			return fmt.Errorf("--expiration must be positive")
		}

		claims := cwt.ClaimsMap{
			iana.CWTClaimSub:   subject,
			iana.CWTClaimAud:   audience,
			iana.CWTClaimExp:   uint64(now.Unix()) + uint64(expSec),
			iana.CWTClaimIat:   uint64(now.Unix()),
			iana.CWTClaimScope: scope,
		}
		if issuer != "" {
			claims[iana.CWTClaimIss] = issuer
		}

		msg := &cose.Sign1Message[cwt.ClaimsMap]{Payload: claims}
		cwtData, err := msg.SignAndEncode(signer, nil)
		if err != nil {
			return fmt.Errorf("sign CWT: %w", err)
		}

		tokenB64 := base64.RawURLEncoding.EncodeToString(cwtData)

		outputJSON, _ := cmd.Flags().GetBool("json")
		if outputJSON {
			if err := printJSON(cmd, map[string]any{
				"token":      tokenB64,
				"subject":    subject,
				"audience":   audience,
				"scope":      scope,
				"issued_at":  now.Unix(),
				"expiration": now.Unix() + expSec,
			}); err != nil {
				return err
			}
		} else {
			_, err := fmt.Fprintf(cmd.OutOrStdout(), "Token:      %s\nSubject:    %s\nAudience:   %s\nScope:      %s\nIssued At:  %s\nExpires At: %s\n",
				tokenB64, subject, audience, scope, now.UTC().Format(time.RFC3339), time.Unix(now.Unix()+expSec, 0).UTC().Format(time.RFC3339))
			return err
		}
		return nil
	},
}

func readPrivateKeyData(keyInput string) ([]byte, error) {
	encodedKey, sourceLabel, err := resolvePrivateKeyInput(keyInput)
	if err != nil {
		return nil, err
	}

	keyData, err := decodeBase64KeyString(encodedKey)
	if err != nil {
		if sourceLabel == "" {
			return nil, fmt.Errorf("decode private key: %w", err)
		}
		return nil, fmt.Errorf("decode private key from %s: %w", sourceLabel, err)
	}

	return keyData, nil
}

func resolvePrivateKeyInput(keyInput string) (encodedKey string, sourceLabel string, err error) {
	keyInput = strings.TrimSpace(keyInput)
	if keyInput == "" {
		return "", "", fmt.Errorf("empty private key input")
	}

	if strings.HasPrefix(keyInput, "@") {
		path := strings.TrimSpace(strings.TrimPrefix(keyInput, "@"))
		if path == "" {
			return "", "", fmt.Errorf("empty key file path after '@'")
		}

		encodedKey, err := readPrivateKeyFile(path)
		if err != nil {
			return "", "", err
		}

		return encodedKey, fmt.Sprintf("file %q", path), nil
	}

	info, err := os.Stat(keyInput)
	if err == nil {
		if info.IsDir() {
			return "", "", fmt.Errorf("key file %q is a directory", keyInput)
		}

		encodedKey, err := readPrivateKeyFile(keyInput)
		if err != nil {
			return "", "", err
		}
		return encodedKey, fmt.Sprintf("file %q", keyInput), nil
	}
	if !os.IsNotExist(err) {
		return "", "", fmt.Errorf("inspect key file %q: %w", keyInput, err)
	}

	return keyInput, "", nil
}

func readPrivateKeyFile(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read key file %q: %w", path, err)
	}

	encodedKey := normalizeBase64Input(string(data))
	if encodedKey == "" {
		return "", fmt.Errorf("key file %q is empty", path)
	}
	return encodedKey, nil
}

func decodeBase64KeyString(value string) ([]byte, error) {
	value = normalizeBase64Input(value)
	if value == "" {
		return nil, fmt.Errorf("empty private key input")
	}

	encodings := []*base64.Encoding{
		base64.RawURLEncoding,
		base64.URLEncoding,
		base64.RawStdEncoding,
		base64.StdEncoding,
	}

	var lastErr error
	for _, encoding := range encodings {
		data, err := encoding.DecodeString(value)
		if err == nil {
			return data, nil
		}
		lastErr = err
	}

	return nil, fmt.Errorf("expected base64 or base64url content: %w", lastErr)
}

func normalizeBase64Input(value string) string {
	return strings.Join(strings.Fields(value), "")
}

func init() {
	cwtCmd.Flags().String("key", "", "Ed25519 private key as base64/base64url-encoded CBOR, or @file/path to a file containing it (env: ANDA_CWT_KEY)")
	cwtCmd.Flags().String("subject", os.Getenv("ANDA_CWT_SUBJECT"), "Subject claim - user/principal ID (env: ANDA_CWT_SUBJECT)")
	cwtCmd.Flags().String("audience", os.Getenv("ANDA_CWT_AUDIENCE"), "Audience claim - space ID or '*' (env: ANDA_CWT_AUDIENCE)")
	cwtCmd.Flags().String("scope", envOrDefault("ANDA_CWT_SCOPE", "read"), "Scope claim: read, write, * (env: ANDA_CWT_SCOPE)")
	cwtCmd.Flags().String("issuer", os.Getenv("ANDA_CWT_ISSUER"), "Issuer claim (env: ANDA_CWT_ISSUER)")
	cwtCmd.Flags().Int64("expiration", 3600, "Token expiration in seconds (default: 3600)")
	cwtCmd.Flags().Bool("json", false, "Output in JSON format")
	rootCmd.AddCommand(cwtCmd)
}
